# Function Call Logger (fcl).
[workspace]
resolver = "3"

members = [ "code_commons",
    "fcl", "fcl_decorators",                  # Rust code.
    "fcl_proc_macros", "fcl_traits",      # Proc macros. Compiled before the actual compilation of other crates. 
    "user",                 # Bin crate to run/test the fcl.
]
