[package]
name = "fcl"
version = "0.1.0"
edition = "2024"

[dependencies]
fcl_traits = { path = "../fcl_traits" }
fcl_decorators = { path = "../fcl_decorators" }
call_graph = { path = "../call_graph" }
fcl_proc_macros = { path = "../fcl_proc_macros" }
