[package]
name = "fcl"
version = "0.1.0"
edition = "2024"

[dependencies]
code_commons = { path = "../code_commons" }
filedescriptor = "0.8.3"
tempfile = "3.20.0"
fcl_proc_macros = { path = "../fcl_proc_macros", features = ["singlethreaded"] }

[features]
singlethreaded = []
minimal_writer = [ "singlethreaded" ]